name: PBS Pro Container Workflow

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      pbspro-container:
        image: pbspro/pbspro
        ports:
          - 22/tcp
        options: --name pbs -h pbs -e PBS_START_MOM=1

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Run PBS Pro Container
        run: |
          docker exec -it pbspro-container bash

      - name: Configure PBS Pro
        run: |
          docker exec -it pbspro-container qmgr -c "create node pbs"
          docker exec -it pbspro-container qmgr -c "set node pbs queue=workq"

      - name: Submit a Job
        run: |
          docker exec -it pbspro-container su pbsuser
          docker exec -it pbspro-container cd
          docker exec -it pbspro-container qsub -- /bin/sleep 10

      - name: View Job Status
        run: |
          docker exec -it pbspro-container qstat
