name: Install OpenPBS

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  install_openpbs:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install -e ".[test,psij]"
     
      - name: Download and Install OpenPBS
        run: |
          python -V
          export LDFLAGS="-Wl,--copy-dt-needed-entries"
          C_INCLUDE_PATH="/usr/include/python3.8/:$PATH"
          export C_INCLUDE_PATH
          CPLUS_INCLUDE_PATH="/usr/include/python3.8/:$PATH"
          export CPLUS_INCLUDE_PATH
          mkdir -p ~/Downloads
          cd ~/Downloads/
          cd ~/pydra/
          pytest -v --psij=pbspro pydra/engine --cov pydra --cov-config .coveragerc --cov-report xml:cov.xml
