name: SLURM

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: giovtorres/docker-centos7-slurm:latest

    steps:
    - name: Disable etelemetry
      run: echo "NO_ET=TRUE" >> $GITHUB_ENV
    - uses: actions/checkout@v3
    - name: Pull docker image
      run: |
        docker pull $DOCKER_IMAGE
        # Have image running in background
        docker run -it -h slurmctl --cap-add sys_admin -d --name slurm -v `pwd`:/pydra -e NO_ET=$NO_ET $DOCKER_IMAGE
    - name: Setup Python
      run: |
        docker exec slurm bash -c "pip3.9 install --upgrade pip && pip3.9 install -e /pydra[test] && python3.9 -c 'import pydra; print(pydra.__version__)'"
    - name: Run pytest
      run: docker exec slurm bash -c "pytest --color=yes -vs -n auto --cov pydra --cov-config /pydra/.coveragerc --cov-report xml:/pydra/cov.xml --doctest-modules /pydra/pydra"
    - name: Upload to codecov
      run: |
        docker exec slurm bash -c "codecov --root /pydra -f /pydra/cov.xml -F unittests"
        docker rm -f slurm