name: PBS Pro Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Start PBS Pro container
      run: |
        docker run -itd --name pbs -h pbs -e PBS_START_MOM=1 pbspro/pbspro bash
      continue-on-error: true

    - name: Configure PBS Pro
      run: |
        docker exec -it pbs qmgr -c "create node pbs"
        docker exec -it pbs qmgr -c "set node pbs queue=workq"

    - name: Switch to pbsuser
      run: |
        docker exec -it pbs su - pbsuser

    - name: Submit a job
      run: |
        docker exec -it pbs qsub -- /bin/sleep 10
        docker exec -it pbs qstat

    - name: Stop and remove PBS Pro container
      run: |
        docker stop pbs
        docker rm pbs
