name: Pydra

on:
  push:
    branches:
      - master
  pull_request:


defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']
      fail-fast: false
    runs-on: ${{ matrix.os }}


    steps:
    - uses: actions/checkout@v2
    - name: Disable etelemetry
      run:  echo "NO_ET=TRUE" >> $GITHUB_ENV
    - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Update build tools
      run: python -m pip install --upgrade pip build

    - name: Build pydra
      run: python -m build


    - name: Install Pydra tests dependencies
      run: pip install "$( ls dist/pydra*.whl )[test]"


    - name: Pytest
      run: pytest -vs -n auto --cov pydra  --cov-config .coveragerc --cov-report xml:cov.xml --doctest-modules pydra


    - name: Upload to codecov
      run: codecov -f cov.xml -F unittests -e GITHUB_WORKFLOW
