name: Install OpenPBS

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  install_openpbs:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Packages
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc make libtool libhwloc-dev libx11-dev libxt-dev libedit-dev libical-dev ncurses-dev perl tcl-dev tk-dev swig libexpat-dev libssl-dev libxext-dev libxft-dev autoconf automake expat libedit2 sendmail-bin sudo tcl tk

      - name: Install PostgreSQL
        run: |
          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          sudo apt-get update
          sudo apt-get -y install postgresql

      - name: Install PostgreSQL Dependencies
        run: |
          sudo apt-get install -y postgresql-server-dev-all postgresql-contrib

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.7

      - name: Download and Install OpenPBS
        run: |
          mkdir -p ~/Downloads
          cd ~/Downloads/
          sudo wget https://github.com/openpbs/openpbs/archive/refs/tags/v20.0.1.tar.gz
          tar -xpvf v20.0.1.tar.gz
          cd openpbs-20.0.1/
          ./autogen.sh
          ./configure --prefix=/opt/pbs
          make
          sudo make install
          sudo /opt/pbs/libexec/pbs_postinstall
          sudo chmod 4755 /opt/pbs/sbin/pbs_iff /opt/pbs/sbin/pbs_rcp
          sudo /etc/init.d/pbs start
          . /etc/profile.d/pbs.sh

      - name: Test OpenPBS
        run: |
          qstat -B
          echo "sleep 60" | qsub
          qstat -a
