name: Install OpenPBS

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  install_openpbs:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install Packages
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc make libtool libhwloc-dev libx11-dev libxt-dev libedit-dev libical-dev ncurses-dev perl tcl-dev tk-dev swig libexpat-dev libssl-dev libxext-dev libxft-dev autoconf automake expat libedit2 sendmail-bin sudo tcl tk mlocate python-dev python3-dev libpython3.8-dev
      
      - name: Install PostgreSQL Dependencies
        run: |
          locate Python.h

