name: PBS Pro Container Workflow

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: pbspro/pbspro
      options: --name pbs -h pbs -e PBS_START_MOM=1

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Run PBS Pro Container
        run: docker exec -it pbs bash

      - name: Configure PBS Pro
        run: |
          docker exec -it pbs qmgr -c "create node pbs"
          docker exec -it pbs qmgr -c "set node pbs queue=workq"

      - name: Submit a Job
        run: |
          docker exec -it pbs su pbsuser
          docker exec -it pbs cd
          docker exec -it pbs qsub -- /bin/sleep 10

      - name: View Job Status
        run: docker exec -it pbs qstat
